---
title: "R Notebook"
output: html_notebook
---

Define a vector named a
```{r}
a <- c(1,1,2,4,3,5,2,1,10,7)
```

R is Case Sensitive
```{r}
a[4]
a[1:4]
a[a>2] # 2보다 큰 수만
a[-1] # 앞의 첫 자리 제외
rep(1,3) # 1을 3번
```

```{r}
seq(1,3,0.5)
seq(1,3,by=0.5)
seq(1,3,length.out = 4) # 숫자 n개 나오도록
```

```{r}
c(a, 1:10) #a에 다 1부터 10까지의 값 추가
length(a) # 길이
cbind(a, 1:10) # column binding
rbind(a, a) # row binding
sort(a)
```
```{r}
a[1:3] <- 10 # 첫 자리부터 세 번째 자리까지 값 10 추가
a
```

```{r}
a[c(-1,2)] # R에서 음수는 빼는 거, 뒤에서 세는거 아냐
```
```{r}
a[c(1, 4)]
```

```{r}
mean(a)
sum(a)
cumsum(a) # n자리에서 1부터 n까지의 값 더한 값을 저장
prod(a)
```

```{r}
rowers <- read.table("C:/Users/korea/Documents/Project/Practice/rowers96.dat", header = TRUE, row.names = NULL, sep = ";", stringsAsFactors = TRUE)
```
# stringsAsFactors = FALSE
data.frame()으로 데이터프레임을 생성할 때, 

변수에 문자가 있을 경우 자동으로 factor타입으로 변환된다.

하지만 factor 변수는 연산이 되지 않으므로 stringsAsFactors() 함수를 써서 factor타입으로 변환되지 않게 한다.

```{r}
View(rowers)
```

```{r}
setwd("C:/Users/korea/Documents/Project/Practice/")
rowers <- read.table("rowers96.dat", header = TRUE, row.names = NULL, sep = "\t")
```

```{r}
rowers <- read.csv("C:/Users/korea/Documents/Project/Practice/rowers96.dat", header = TRUE, row.names = NULL, sep = "\t")
```


```{r}
edit(rowers) # 수제 편집
```


```{r}
names(rowers) # column 이름들 vector로 추출
```


```{r}
rowers[,1] # 첫 번째 column
rowers[1,] # 첫 번째 row
```


```{r}
rowers$name # 각 column들 추출
rowers$event
rowers$weight
mean(rowers$weight)
```

```{r}
attach(rowers) #rowers의 자료구조를 R에 연결
name
event
weight
detach(rowers)
```

```{r}
nrow(rowers) # row 크기 세기
weightkg <- weight*0.454 # 값 새로이 저장
weightkg
boxplot(weightkg)
plot(weightkg, event)
```

```{r}
help.start()
?var
```


```{r}
help.search("qq plot")
```

```{r}
summary(cars)
```
```{r pressure, echo=FALSE}
plot(pressure)
```




### Seungchan Header 2

#### Seungchan Header 3

##### Seungchan Header 4

**Statistics**

$M_1 = 10$