def frequencyTable(text, k):
    freqMap = dict()
    textlen = len(text)
    
    for i in range(textlen-k+1):
        pattern = text[i:i+k]
        if pattern not in freqMap.keys():
            freqMap[pattern] = 1
        else:
            freqMap[pattern] += 1
    return freqMap

def maxMap(freqMap):
    maxCount = 0
    
    for key in freqMap.keys():
        if (maxCount < freqMap[key]):
            maxCount = freqMap[key] 
    return maxCount

def betterFrequentWords(text, k):
    frequentPatterns = list()
    freqMap = frequencyTable(text, k)
    max = maxMap(freqMap)
    for pattern in freqMap.keys():
        if (freqMap[pattern] == max):
            frequentPatterns.append(pattern)
    return ' '.join(frequentPatterns)

input1 = "TGCTTGTGTCAAATCGCCTCAAATCGCCTCAAGGGCTACAAGGGCTACTGGCGCTCAAAATCGCCTCAAGGGCTACTGGCGCTCAAAATCGCCTCTTTTGGGATTTTGGGAAAGGGCTACTTTTGGGATGGCGCTCATGCTTGTGTCTGCTTGTGTCAAGGGCTACAAATCGCCTCAAATCGCCTCTGCTTGTGTCAAATCGCCTCTGCTTGTGTCAAGGGCTACAAATCGCCTCAAGGGCTACAAATCGCCTCAAGGGCTACAAATCGCCTCTGGCGCTCAAAGGGCTACTTTTGGGAAAATCGCCTCTTTTGGGATGGCGCTCATGCTTGTGTCTGCTTGTGTCTGCTTGTGTCTGGCGCTCAAAATCGCCTCTTTTGGGAAAATCGCCTCAAGGGCTACTGGCGCTCATTTTGGGAAAGGGCTACTTTTGGGATTTTGGGAAAGGGCTACAAGGGCTACTTTTGGGATGGCGCTCATGCTTGTGTCAAATCGCCTCAAGGGCTACTTTTGGGATGCTTGTGTCTGCTTGTGTCAAGGGCTACAAATCGCCTCTTTTGGGAAAATCGCCTCTGCTTGTGTCAAATCGCCTCAAATCGCCTCTGGCGCTCATGCTTGTGTCTGGCGCTCAAAGGGCTACTGGCGCTCAAAATCGCCTCAAATCGCCTCTGGCGCTCATGCTTGTGTCTGGCGCTCATGGCGCTCATGCTTGTGTCAAATCGCCTCTTTTGGGAAAATCGCCTCTGCTTGTGTCTTTTGGGATGCTTGTGTCTGCTTGTGTCTGGCGCTCAAAATCGCCTCTGCTTGTGTCTGCTTGTGTCAAATCGCCTCTGGCGCTCAAAATCGCCTCTGGCGCTCAAAGGGCTACAAGGGCTACAAATCGCCTCTGGCGCTCATTTTGGGAAAGGGCTACAAGGGCTACTGGCGCTCATGCTTGTGTCAAATCGCCTCTTTTGGGATGCTTGTGTC"
input2 = 14
#print(betterFrequentWords(input1, input2))
